vocab_size: 50000
max_seq_len: 2048
d_model: 2048
n_layers: 24
n_heads: 16
ffn_mult: 4.0
rope_base: 10000
train:
  micro_bsz: 1
  grad_accum: 24
  epochs: 1
  lr: 2e-4
  warmup: 400
  bf16: true
  grad_checkpoint: true
  compile: true
