"""
AI package for Flame Prime.

This package contains modules that power the Flame Prime reflex system.  The
``daily_modules`` subpackage will be populated automatically with modules
generated by ``daily_module_generator.py``.  You can import newly generated
modules at runtime to access the daily weights.
"""

from importlib import import_module
from pathlib import Path
from typing import Optional


def load_latest_daily_module() -> Optional[object]:
    """
    Dynamically import the most recent daily reflex module.

    Returns:
        The imported module object or ``None`` if no modules are available.
    """
    daily_dir = Path(__file__).resolve().parent / "daily_modules"
    if not daily_dir.exists():
        return None
    modules = sorted(
        [p.stem for p in daily_dir.glob("*_flame_reflex.py")],
        reverse=True,
    )
    if not modules:
        return None
    latest_module = modules[0]
    return import_module(f"flame_prime.ai.daily_modules.{latest_module}")
